#include "constantes.h"

const string Constantes::NOM_AUX1 = "aux1.bin";
const string Constantes::NOM_AUX2 = "aux2.bin";
const string Constantes::NOM_AUX2_ORD = "aux2Ord.bin";
const string Constantes::NORMAS = "normas.bin";
const string Constantes::NOM_STREAMTERMS = "terminos.bin";
const string Constantes::NOM_LEXICO = "lexico.bin";
const string Constantes::NOM_PUNT = "punteros.bin";
const int Constantes::LECTURA_BIN = 0;
const int Constantes::ESCRITURA_BIN = 1;
const int Constantes::LECT_Y_ESC_BIN = 2;
const string Constantes::STOPWORDS = "stopwords.txt"; 