#ifndef CONSTANTES_H
#define CONSTANTES_H

#define MAX_LONG_PAL 64

#include <string>
using namespace std;

class Constantes{
public:
	static const string NOM_AUX1;
	static const string NOM_AUX2;
	static const string NOM_AUX2_ORD;
	static const string NORMAS;
	static const string NOM_STREAMTERMS;
	static const string NOM_LEXICO;
	static const string NOM_PUNT;
	static const int ESCRITURA_BIN;
	static const int LECTURA_BIN;
	static const int LECT_Y_ESC_BIN;
	static const string STOPWORDS; 
	   
};

#endif
